name: CVMFS Image Management

inputs:
  github_token:
    description: 'a PAT so the bot can git push to WIPACrepo/cvmfs-actions'
    required: true
  dest_dir:
    description: 'the CVMFS sub-directory to place/remove images'
    required: true
  docker_tags:
    description: 'the list of Docker image tags requested to be built on CVMFS'
    default: ''
  include_docker_repo:
    description: 'whether to include the docker repo when inserting into CVMFS dir'
    type: boolean
    default: 'true'
  delete_image_tags:
    description: 'DELETION MODE: Image tag to match (full tag or prefix for SHA matching)'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Check Inputs
      run: |
        if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
          if [[ -z "${{ inputs.dest_dir }}" || -n "${{ inputs.docker_tags }}" ]]; then
            echo "::error::Input Error: 'delete_image_tags' requires 'dest_dir' and forbids 'docker_tags'."
            exit 1
          fi
        elif [[ -z "${{ inputs.docker_tags }}" ]]; then
          echo "::error::Input Error: 'docker_tags' is required for build mode."
          exit 1
        fi
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Checkout WIPACrepo/cvmfs-actions
      uses: actions/checkout@v3
      with:
        repository: WIPACrepo/cvmfs-actions
        token: ${{ inputs.github_token }}

    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash

    - name: Request Removal(s) on CVMFS
      if: inputs.delete_image_tags != ''
      run: |
        python3 ${{ github.action_path }}/request_removal.py \
            --dest-dir "${{ inputs.dest_dir }}" \
            --delete-image-tags "${{ inputs.delete_image_tags }}"
        
        git add docker_images.txt || true
        git commit -m "<bot> docker_images.txt: request removal (${{ inputs.delete_image_tags }})" || true
      shell: bash

    - name: Push changes
      run: |
        status=`git status 2>&1 | tee`
        ahead=`echo -n "${status}" | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git push
      shell: bash
