name: CVMFS Image Management

inputs:
  github_token:
    description: 'a PAT so the bot can git -C "$GITHUB_WORKSPACE/.cvmfs-actions" push to WIPACrepo/cvmfs-actions'
    required: true
  dest_dir:
    description: 'the CVMFS sub-directory to place/remove images'
    required: true
  build_images:
    description: |
      BUILD MODE:
        The Docker image(s) to be built on CVMFS  
        Image format:
          Docker Hub            : icecube/skymap_scanner:4.0.0 
          GH Container Registry : ghcr.io/wipacrepo/iceprod:3.0.52
      HINT: use 'needs.docker.outputs.tags' from https://github.com/docker/metadata-action
    default: ''
  delete_image_nametags:
    description: |
      DELETION MODE: 
        Newline-delimited images (name + tag) to remove, indicated verbatim or using known patterns.
        Example:
          delete_image_nametags: |
            foo:v1.2.3
            foo:main-[SHA]
    default: ''

runs:
  using: "composite"
  steps:
    - name: internal logic (set env vars)
      run: |
        # step: internal logic (set env vars)
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        echo "DOCKER_IMAGES_FILE=docker_images.txt" >> "$GITHUB_ENV"

      shell: bash

    - name: Check Inputs
      run: |
        # step: Check Inputs
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # UNSUPPORTED INPUT
        if [[ -n "${{ inputs.include_docker_repo }}" ]]; then
          echo "::error::Input Error: 'include_docker_repo' has been deprecated -- rely solely on 'dest_dir'."
          exit 1
        fi
        if [[ -n "${{ inputs.docker_tags }}" ]]; then
          echo "::error::Input Error: 'docker_tags' has been deprecated -- use 'build_images'."
          exit 1
        fi
        if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
          echo "::error::Input Error: 'delete_image_nametags' has been deprecated -- use 'delete_image_nametags'."
          exit 1
        fi
        
        # REQUIRED INPUT
        if [[ -z "${{ inputs.dest_dir }}" ]]; then
          echo "::error::Input Error: 'dest_dir' is required."
          exit 1
        fi
        
        # DELETION MODE?
        if [[ -n "${{ inputs.delete_image_nametags }}" ]]; then
          if [[ -n "${{ inputs.build_images }}" ]]; then
            echo "::error::Input Error: 'delete_image_nametags' forbids 'build_images'."
            exit 1
          fi
        # CREATION MODE?
        elif [[ -z "${{ inputs.build_images }}" ]]; then
          echo "::error::Input Error: 'build_images' is required for build mode."
          exit 1
        fi

      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # NOTE: update, someday

    - name: Checkout WIPACrepo/cvmfs-actions
      uses: actions/checkout@v3
      with:
        repository: WIPACrepo/cvmfs-actions
        token: ${{ inputs.github_token }}  # so job can git -C "$GITHUB_WORKSPACE/.cvmfs-actions" push
        path: .cvmfs-actions  # access at $GITHUB_WORKSPACE/.cvmfs-actions

    - name: Git config
      run: |
        # step: Git config
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        git -C "$GITHUB_WORKSPACE/.cvmfs-actions" config user.name github-actions
        git -C "$GITHUB_WORKSPACE/.cvmfs-actions" config user.email github-actions@github.com
      shell: bash

    - name: Request Build(s) on CVMFS
      if: inputs.delete_image_nametags == ''
      run: |
        # step: Request Build(s) on CVMFS
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # update and commit for each tag
        for IMAGE in "${{ inputs.build_images }}"; do
          echo "$IMAGE"
          echo "##[group]updating $DOCKER_IMAGES_FILE"
          python3 $GITHUB_WORKSPACE/.cvmfs-actions/request_build.py \
              --image-uri "$IMAGE" \
              --dest-dir ${{ inputs.dest_dir }}
          echo "##[endgroup]"
          git -C "$GITHUB_WORKSPACE/.cvmfs-actions" add "$DOCKER_IMAGES_FILE" || true
          git -C "$GITHUB_WORKSPACE/.cvmfs-actions" commit -m "<bot> build: $IMAGE" || true
        done

      shell: bash

    - name: Request Removal(s) on CVMFS
      if: inputs.delete_image_nametags != ''
      run: |
        # step: Request Removal(s) on CVMFS
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # load into array (w/ trimming)
        mapfile -t DELETE_IMAGES < <(printf '%s\n' "${{ inputs.delete_image_nametags }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
        
        # request all matches for each tag (pattern)
        for IMAGE in "${DELETE_IMAGES[@]}"; do
          echo "$IMAGE"
          echo "##[group]updating $DOCKER_IMAGES_FILE"
          python3 $GITHUB_WORKSPACE/.cvmfs-actions/request_removal.py \
            --dest-dir "${{ inputs.dest_dir }}" \
            --image-nametag-pattern "$IMAGE"
          echo "##[endgroup]"
          git -C "$GITHUB_WORKSPACE/.cvmfs-actions" add "$DOCKER_IMAGES_FILE" || true
          git -C "$GITHUB_WORKSPACE/.cvmfs-actions" commit -m "<bot> remove: $IMAGE" || true
        done

      shell: bash

    - name: View changes
      run: |
        # step: View changes
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        git -C "$GITHUB_WORKSPACE/.cvmfs-actions" diff --unified=0 origin/main...HEAD

      shell: bash

    - name: Push changes
      run: |
        # step: Push changes
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        status=`git -C "$GITHUB_WORKSPACE/.cvmfs-actions" status 2>&1 | tee`
        ahead=`echo -n "${status}" | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git -C "$GITHUB_WORKSPACE/.cvmfs-actions" push
        
        echo "::notice::see https://github.com/WIPACrepo/cvmfs-actions/blob/main/$DOCKER_IMAGES_FILE"

      shell: bash
