name: CVMFS Image Management

inputs:
  github_token:
    description: 'a PAT so the bot can git push to WIPACrepo/cvmfs-actions'
    required: true
  dest_dir:
    description: 'the CVMFS sub-directory to place/remove images'
    required: true
  docker_tags:
    description: 'the list of Docker image tags requested to be built on CVMFS'  # use `${{ needs.docker.outputs.tags }}`
    default: ''
  delete_image_tags:
    description: |
      DELETION MODE: Newline-delimited image tags to remove (as literal names or known patterns).
      Example:
        delete_image_tags: |
          v1.2.3
          main-[SHA]
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set Global Env Vars
      run: |
        # step: Set Global Env Vars
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        echo "DOCKER_IMAGES_FILE=./docker_images.txt" >> "$GITHUB_ENV"

      shell: bash

    - name: Check Inputs
      run: |
        # step: Check Inputs
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # UNSUPPORTED INPUT
        if [[ -n "${{ inputs.include_docker_repo }}" ]]; then
          echo "::error::Input Error: 'include_docker_repo' has been deprecated -- rely solely on 'dest_dir'."
          exit 1
        fi
        
        # REQUIRED INPUT
        if [[ -z "${{ inputs.dest_dir }}" ]]; then
          echo "::error::Input Error: 'dest_dir' is required."
          exit 1
        fi
        
        # DELETION MODE?
        if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
          if [[ -n "${{ inputs.docker_tags }}" ]]; then
            echo "::error::Input Error: 'delete_image_tags' forbids 'docker_tags'."
            exit 1
          fi
        # CREATION MODE?
        elif [[ -z "${{ inputs.docker_tags }}" ]]; then
          echo "::error::Input Error: 'docker_tags' is required for build mode."
          exit 1
        fi

      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # NOTE: update, someday

    - name: Checkout WIPACrepo/cvmfs-actions
      uses: actions/checkout@v3
      with:
        repository: WIPACrepo/cvmfs-actions
        token: ${{ inputs.github_token }}  # so job can git push

    - name: Git config
      run: |
        # step: Git config
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash

    - name: Request Build(s) on CVMFS
      if: inputs.delete_image_tags == ''
      run: |
        # step: Request Build(s) on CVMFS
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # update and commit for each tag
        for IMAGE in "${{ inputs.docker_tags }}"; do
          echo "$IMAGE"
          echo "##[group]updating $DOCKER_IMAGES_FILE"
          python3 ${{ github.action_path }}/request_build.py \
              --image-nametag "$IMAGE" \
              --dest-dir ${{ inputs.dest_dir }}
          echo "##[endgroup]"
          git add "$DOCKER_IMAGES_FILE" || true
          git commit -m "<bot> build: $IMAGE" || true
        done

      shell: bash

    - name: Request Removal(s) on CVMFS
      if: inputs.delete_image_tags != ''
      run: |
        # step: Request Removal(s) on CVMFS
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # load into array (w/ trimming)
        mapfile -t DELETE_IMAGES < <(printf '%s\n' "${{ inputs.delete_image_tags }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
        
        # request all matches for each tag (pattern)
        for IMAGE in "${DELETE_IMAGES[@]}"; do
          echo "$IMAGE"
          echo "##[group]updating $DOCKER_IMAGES_FILE"
          python3 ${{ github.action_path }}/request_removal.py \
            --dest-dir "${{ inputs.dest_dir }}" \
            --image-nametag-pattern "$IMAGE"
          echo "##[endgroup]"
          git add "$DOCKER_IMAGES_FILE" || true
          git commit -m "<bot> remove: $IMAGE" || true
        done

      shell: bash

    - name: View changes
      run: |
        # step: View changes
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        git log origin/main..HEAD --patch --reverse

      shell: bash

    - name: Push changes
      run: |
        # step: Push changes
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        status=`git status 2>&1 | tee`
        ahead=`echo -n "${status}" | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git push

      shell: bash
